package org.omg.schema.spec.cts2._1_0.wsdl.codesystemcatalogreadservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import edu.mayo.cts2.framework.model.service.core.NameOrURI;
import edu.mayo.cts2.framework.model.service.core.QueryControl;
import edu.mayo.cts2.framework.model.service.core.ReadContext;

/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Feb 03 14:12:13 CST 2012
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://schema.omg.org/spec/CTS2/1.0/wsdl/CodeSystemCatalogReadServices", name = "CodeSystemCatalogReadServicePortType")
public interface CodeSystemCatalogReadServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://schema.omg.org/spec/CTS2/1.0/wsdl/CodeSystemCatalogReadServices", className = "org.omg.schema.spec.cts2._1_0.wsdl.codesystemcatalogreadservices.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://schema.omg.org/spec/CTS2/1.0/wsdl/CodeSystemCatalogReadServices", className = "org.omg.schema.spec.cts2._1_0.wsdl.codesystemcatalogreadservices.ReadResponse")
    @WebMethod
    public edu.mayo.cts2.framework.model.codesystem.CodeSystemCatalogEntry read(
        @WebParam(name = "codeSystemId", targetNamespace = "")
        NameOrURI codeSystemId,
        @WebParam(name = "queryControl", targetNamespace = "")
        QueryControl queryControl,
        @WebParam(name = "context", targetNamespace = "")
        ReadContext context
    );

 
}
